### ISSUE TITLE
Coinjoin FTW

### ISSUE THREAD

**Issue by alwaysAn0n** [imaginaryusername/payshuffle#1]
Thanks for working on Coinjoin

@GitCash send @imaginaryusername 1 usd

**Comment by alwaysAn0n** [comment]
@GitCash send @ConsensusBot 1 usd

**Comment by alwaysAn0n** [comment]
@GitCash send @imaginaryusername 1 usd

**Comment by GitCash** [comment]
Hey **imaginaryusername**, user **alwaysAn0n** tipped you **9090 bits** in Bitcoin Cash ( ~ **$1** ).

*[Click here to claim it!](https://gitcash.io/claim/imaginaryusername)*

You can also add the "thumbs down" reaction to **alwaysAn0n**'s comment above to prevent future tips.
